version: '3'

services:
  php:
    build: ./php-fpm
    volumes:
      - './:/var/www/app'
      - './php-fpm/php.ini:/usr/local/etc/php/conf.d/docker-app.ini'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: 'nginx:alpine'
    container_name: webserver
    volumes:
      - './nginx/app.conf:/etc/nginx/conf.d/app.conf'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './:/var/www/app'
    ports:
      - '8080:8080'
    links:
      - php
    depends_on:
      - php
